export const translations = {
  tr: {
    // Navigation
    home: 'Ana Sayfa',
    logout: 'Çıkış',
    logs: 'Loglar',
    panel: 'Panel',

    // Common
    loading: 'Yükleniyor...',
    add: 'Ekle',
    delete: 'Sil',
    active: 'Aktif',
    inactive: 'Pasif',
    enable: 'Etkinleştir',
    disable: 'Devre Dışı',
    label: 'etiket',
    status: 'Durum',
    requests: 'İstek',
    errors_col: 'Hata',
    last_used: 'Son Kullanım',
    actions: 'İşlem',
    model: 'Model',
    provider: 'Sağlayıcı',
    no_data: 'Henüz veri yok',

    // Index page
    meta_desc: 'NVIDIA NIM modellerine Anthropic Messages API ile erişim sağlayan yüksek performanslı proxy sunucu.',
    subtitle: 'NVIDIA NIM uç noktasını Anthropic Messages API olarak sunan proxy',
    access_required: 'Bu proxy\'ye erişim anahtarı gereklidir.',
    register_prompt: 'Erişim anahtarı almak için e-posta adresinizi girin:',
    email_placeholder: 'örnek@mail.com',
    signup: 'kayıt ol',
    code_sent: 'Doğrulama kodu e-posta adresinize gönderildi:',
    code_placeholder: '6 haneli kod',
    verify: 'doğrula',
    token_created: 'Erişim anahtarınız oluşturuldu. Kopyalamak için tıklayın:',
    copied: 'Kopyalandı',
    no_brevo: 'Erişim anahtarı almak için yönetici ile iletişime geçin.',
    stats_header: 'İstatistikler',
    benchmark_header: 'Model Yanıt Süreleri',
    config_header: 'Claude Code Yapılandırması',
    models_header: 'Kullanılabilir Modeller',
    config_single: 'Tek komutla yapılandırın (önerilen):',
    config_start: 'Başlatmak için:',
    config_add_model: 'Diğer modelleri eklemek için:',
    config_details: 'Detaylar:',
    config_alt: 'Alternatif olarak',
    config_edit: 'dosyasını düzenleyin:',
    config_switch: 'Oturum içinde model değiştirmek için:',
    your_key: '&lt;erişim anahtarınız&gt;',
    total_requests: 'Toplam İstek',
    today: 'Bugün',
    active_users: 'Aktif Kullanıcı',
    last_24h: 'Son 24 saat',
    most_used: 'En Çok Kullanılan Modeller',
    short_ttfb: 'Kısa TTFB',
    short_total: 'Kısa Toplam',
    long_ttfb: 'Uzun TTFB',
    long_total: 'Uzun Toplam',
    bench_update: 'Her saat başı güncellenir. TTFB = ilk yanıt süresi, Toplam = tam yanıt süresi.',
    bench_method: 'Metodoloji:',
    bench_method_desc: 'Her model için iki ayrı streaming istek gönderilir. Kısa prompt: tek kelimelik yanıt (max 100 token). Uzun prompt: Python binary search tree implementasyonu (max 2048 token). TTFB, sunucudan gelen ilk byte\'ın alınma süresini; Toplam ise yanıtın tamamen tamamlanma süresini ölçer. Ölçümler NVIDIA NIM API üzerinden yapılır, proxy overhead dahildir.',
    no_bench: 'Benchmark verisi henüz yok',
    no_models: 'Model bulunamadı',
    models_count_suffix: 'model',
    models_load_fail: 'Model listesi yüklenemedi',
    stats_load_fail: 'İstatistikler yüklenemedi',
    error_occurred: 'Bir hata oluştu',
    connection_error: 'Bağlantı hatası',

    // Admin page
    admin_title: 'Anthronim // Yönetim',
    admin_meta: 'Anthronim yönetim paneli.',
    hourly_chart: 'Saatlik İstek Grafiği / Son 24 Saat',
    model_usage: 'Model Kullanımı',
    api_keys: 'API Anahtarları',
    access_keys: 'Erişim Anahtarları',
    benchmark_models: 'Benchmark Modelleri',
    available_models: 'Kullanılabilir Modeller (NVIDIA NIM)',
    active_keys: 'Aktif Anahtar',
    active_tokens: 'Aktif Token',
    error_rate: 'Hata Oranı',
    last_24h_short: 'Son 24 Saat',
    generate: 'Üret',
    model_placeholder: 'model-adi (ör: minimaxai/minimax-m2.5)',
    auto_refresh: 'Otomatik yenileme: 30s',
    no_api_keys: 'Henüz API anahtarı eklenmedi',
    no_access_keys: 'Henüz erişim anahtarı eklenmedi',
    no_bench_models: 'Benchmark modeli eklenmemiş',
    key_col: 'Anahtar',
    token_col: 'Token',
    confirm_delete_key: 'Bu API anahtarını silmek istediğinizden emin misiniz?',
    confirm_delete_token: 'Bu erişim anahtarını silmek istediğinizden emin misiniz?',
    confirm_delete_bench: 'Bu modeli benchmark listesinden silmek istediğinizden emin misiniz?',
    api_error: 'API hatası',

    // Logs page
    logs_title: 'Anthronim // Upstream Loglar',
    logs_meta: 'Anthronim upstream istek logları.',
    logs_heading: 'Anthronim // Upstream Loglar',
    filter_status: 'Durum',
    errors_only: 'Sadece Hatalar',
    all: 'Tümü',
    model_placeholder_logs: 'ör: meta/llama-3...',
    limit: 'Limit',
    date: 'Tarih',
    api_key: 'API Anahtarı',
    access_key: 'Erişim Anahtarı',
    detail: 'Detay',
    no_records: 'Kayıt bulunamadı',
    previous: 'Önceki',
    next: 'Sonraki',
    records_suffix: 'kayıt',

    // Login page
    login_title: 'Anthronim // Giriş',
    login_heading: 'anthronim // giriş',
    username: 'kullanıcı adı',
    password: 'şifre',
    login_btn: 'giriş yap',
    login_invalid: 'Geçersiz kullanıcı adı veya şifre.',
    login_lockout: 'Çok fazla başarısız deneme. Lütfen bekleyin.',

    // Email
    email_subject: 'Anthronim - Doğrulama Kodu',
    email_body: 'Doğrulama kodunuz: {{CODE}}\n\nBu kod 10 dakika geçerlidir.',
  },

  en: {
    // Navigation
    home: 'Home',
    logout: 'Logout',
    logs: 'Logs',
    panel: 'Panel',

    // Common
    loading: 'Loading...',
    add: 'Add',
    delete: 'Delete',
    active: 'Active',
    inactive: 'Inactive',
    enable: 'Enable',
    disable: 'Disable',
    label: 'label',
    status: 'Status',
    requests: 'Requests',
    errors_col: 'Errors',
    last_used: 'Last Used',
    actions: 'Actions',
    model: 'Model',
    provider: 'Provider',
    no_data: 'No data yet',

    // Index page
    meta_desc: 'High-performance proxy server providing access to NVIDIA NIM models via the Anthropic Messages API.',
    subtitle: 'Proxy serving the NVIDIA NIM endpoint as the Anthropic Messages API',
    access_required: 'An access key is required for this proxy.',
    register_prompt: 'Enter your email address to get an access key:',
    email_placeholder: 'example@mail.com',
    signup: 'sign up',
    code_sent: 'A verification code has been sent to your email address:',
    code_placeholder: '6-digit code',
    verify: 'verify',
    token_created: 'Your access key has been created. Click to copy:',
    copied: 'Copied',
    no_brevo: 'Contact the administrator to get an access key.',
    stats_header: 'Statistics',
    benchmark_header: 'Model Response Times',
    config_header: 'Claude Code Configuration',
    models_header: 'Available Models',
    config_single: 'Configure with a single command (recommended):',
    config_start: 'To start:',
    config_add_model: 'To add more models:',
    config_details: 'Details:',
    config_alt: 'Alternatively, edit',
    config_edit: ':',
    config_switch: 'To switch models within a session:',
    your_key: '&lt;your access key&gt;',
    total_requests: 'Total Requests',
    today: 'Today',
    active_users: 'Active Users',
    last_24h: 'Last 24 hours',
    most_used: 'Most Used Models',
    short_ttfb: 'Short TTFB',
    short_total: 'Short Total',
    long_ttfb: 'Long TTFB',
    long_total: 'Long Total',
    bench_update: 'Updated every hour. TTFB = time to first byte, Total = full response time.',
    bench_method: 'Methodology:',
    bench_method_desc: 'Two separate streaming requests are sent for each model. Short prompt: single-word response (max 100 tokens). Long prompt: Python binary search tree implementation (max 2048 tokens). TTFB measures time to first byte from the server; Total measures full response completion time. Measurements are made via the NVIDIA NIM API, proxy overhead included.',
    no_bench: 'No benchmark data yet',
    no_models: 'No models found',
    models_count_suffix: 'models',
    models_load_fail: 'Failed to load model list',
    stats_load_fail: 'Failed to load statistics',
    error_occurred: 'An error occurred',
    connection_error: 'Connection error',

    // Admin page
    admin_title: 'Anthronim // Admin',
    admin_meta: 'Anthronim administration panel.',
    hourly_chart: 'Hourly Request Chart / Last 24 Hours',
    model_usage: 'Model Usage',
    api_keys: 'API Keys',
    access_keys: 'Access Keys',
    benchmark_models: 'Benchmark Models',
    available_models: 'Available Models (NVIDIA NIM)',
    active_keys: 'Active Keys',
    active_tokens: 'Active Tokens',
    error_rate: 'Error Rate',
    last_24h_short: 'Last 24 Hours',
    generate: 'Generate',
    model_placeholder: 'model-name (e.g.: minimaxai/minimax-m2.5)',
    auto_refresh: 'Auto-refresh: 30s',
    no_api_keys: 'No API keys added yet',
    no_access_keys: 'No access keys added yet',
    no_bench_models: 'No benchmark models added',
    key_col: 'Key',
    token_col: 'Token',
    confirm_delete_key: 'Are you sure you want to delete this API key?',
    confirm_delete_token: 'Are you sure you want to delete this access key?',
    confirm_delete_bench: 'Are you sure you want to remove this model from the benchmark list?',
    api_error: 'API error',

    // Logs page
    logs_title: 'Anthronim // Logs',
    logs_meta: 'Anthronim upstream request logs.',
    logs_heading: 'Anthronim // Upstream Logs',
    filter_status: 'Status',
    errors_only: 'Errors Only',
    all: 'All',
    model_placeholder_logs: 'e.g.: meta/llama-3...',
    limit: 'Limit',
    date: 'Date',
    api_key: 'API Key',
    access_key: 'Access Key',
    detail: 'Detail',
    no_records: 'No records found',
    previous: 'Previous',
    next: 'Next',
    records_suffix: 'records',

    // Login page
    login_title: 'Anthronim // Login',
    login_heading: 'anthronim // login',
    username: 'username',
    password: 'password',
    login_btn: 'log in',
    login_invalid: 'Invalid username or password.',
    login_lockout: 'Too many failed attempts. Please wait.',

    // Email
    email_subject: 'Anthronim - Verification Code',
    email_body: 'Your verification code: {{CODE}}\n\nThis code is valid for 10 minutes.',
  },
};

export function renderTemplate(html, lang) {
  const dict = translations[lang] || translations.en;
  return html.replace(/\{\{(\w+)\}\}/g, (_, key) => dict[key] ?? key);
}

export function getLang(req) {
  const cookie = req.headers.cookie || '';
  const match = cookie.split(';').map(c => c.trim()).find(c => c.startsWith('lang='));
  if (match) {
    const val = match.slice(5);
    if (val === 'tr' || val === 'en') return val;
  }
  const accept = req.headers['accept-language'] || '';
  if (accept.startsWith('tr')) return 'tr';
  return 'en';
}
